const mydata = [
    {
        "weather_id": 1,
        "time_of_day": "19:30:00",
        "postal_code": 12345,
        "temperature": "15",
        "dew_point": "8.70",
        "heat_index": "15.20",
        "wind_chill": "10.30",
        "surface_wind": "10",
        "wind_direction": "SW",
        "gust": "8.20",
        "sky_cover": "70.00",
        "precipitation": "100",
        "relative_humidity": "72.50",
        "day": "Monday",
        "time_zone": "EST",
        "date": "2023-03-24",
        "Rain": "Lkly",
        "Thunder": null,
        "Snow": "Ocnl",
        "Freezing_Rain": null,
        "Sleet": "Chc",
        "feels_like": "15",
        "discription": "Cloudy"
    },
    {
        "weather_id": 2,
        "time_of_day": "19:30:00",
        "postal_code": 12345,
        "temperature": "15",
        "dew_point": "8.70",
        "heat_index": "15.20",
        "wind_chill": "10.30",
        "surface_wind": "10",
        "wind_direction": "SW",
        "gust": "8.20",
        "sky_cover": "70.00",
        "precipitation": "100",
        "relative_humidity": "72.50",
        "day": "TUesday",
        "time_zone": "EST",
        "date": "2023-03-24",
        "Rain": "Lkly",
        "Thunder": null,
        "Snow": "Ocnl",
        "Freezing_Rain": null,
        "Sleet": "Chc",
        "feels_like": "15",
        "discription": "Cloudy"
    },
    {
        "weather_id": 3,
        "time_of_day": "19:30:00",
        "postal_code": 12345,
        "temperature": "15",
        "dew_point": "8.70",
        "heat_index": "15.20",
        "wind_chill": "10.30",
        "surface_wind": "10",
        "wind_direction": "SW",
        "gust": "8.20",
        "sky_cover": "70.00",
        "precipitation": "100",
        "relative_humidity": "72.50",
        "day": "Wednesday",
        "time_zone": "EST",
        "date": "2023-03-24",
        "Rain": "Lkly",
        "Thunder": null,
        "Snow": "Ocnl",
        "Freezing_Rain": null,
        "Sleet": "Chc",
        "feels_like": "15",
        "discription": "Cloudy"
    },
    {
        "weather_id": 4,
        "time_of_day": "19:30:00",
        "postal_code": 12345,
        "temperature": "15",
        "dew_point": "8.70",
        "heat_index": "15.20",
        "wind_chill": "10.30",
        "surface_wind": "10",
        "wind_direction": "SW",
        "gust": "8.20",
        "sky_cover": "70.00",
        "precipitation": "100",
        "relative_humidity": "72.50",
        "day": "Thursday",
        "time_zone": "EST",
        "date": "2023-03-24",
        "Rain": "Lkly",
        "Thunder": null,
        "Snow": "Ocnl",
        "Freezing_Rain": null,
        "Sleet": "Chc",
        "feels_like": "15",
        "discription": "Cloudy"
    },
    {
        "weather_id": 5,
        "time_of_day": "19:30:00",
        "postal_code": 12345,
        "temperature": "15",
        "dew_point": "8.70",
        "heat_index": "15.20",
        "wind_chill": "10.30",
        "surface_wind": "10",
        "wind_direction": "SW",
        "gust": "8.20",
        "sky_cover": "70.00",
        "precipitation": "100",
        "relative_humidity": "72.50",
        "day": "Friday",
        "time_zone": "EST",
        "date": "2023-03-24",
        "Rain": "Lkly",
        "Thunder": null,
        "Snow": "Ocnl",
        "Freezing_Rain": null,
        "Sleet": "Chc",
        "feels_like": "15",
        "discription": "Cloudy"
    },
    {
        "weather_id": 6,
        "time_of_day": "19:30:00",
        "postal_code": 12345,
        "temperature": "15",
        "dew_point": "8.70",
        "heat_index": "15.20",
        "wind_chill": "10.30",
        "surface_wind": "10",
        "wind_direction": "SW",
        "gust": "8.20",
        "sky_cover": "70.00",
        "precipitation": "100",
        "relative_humidity": "72.50",
        "day": "Saturday",
        "time_zone": "EST",
        "date": "2023-03-24",
        "Rain": "Lkly",
        "Thunder": null,
        "Snow": "Ocnl",
        "Freezing_Rain": null,
        "Sleet": "Chc",
        "feels_like": "15",
        "discription": "Cloudy"
    },
    {
        "weather_id": 7,
        "time_of_day": "19:30:00",
        "postal_code": 12345,
        "temperature": "15",
        "dew_point": "8.70",
        "heat_index": "15.20",
        "wind_chill": "10.30",
        "surface_wind": "10",
        "wind_direction": "WS",
        "gust": "8.20",
        "sky_cover": "70.00",
        "precipitation": "100",
        "relative_humidity": "72.50",
        "day": "Sunday",
        "time_zone": "EST",
        "date": "2023-03-24",
        "Rain": "Lkly",
        "Thunder": null,
        "Snow": "Ocnl",
        "Freezing_Rain": null,
        "Sleet": "Chc",
        "feels_like": "15",
        "discription": "Cloudy"
    }
]

export default mydata;